baseURL = 'https://coldnoise.net/'
languageCode = "en-US"
title = "John Boyd"

theme = "hugo-trainsh"

# URL normalization
disablePathToLower = false # ensure all paths are lowercased
removePathAccents = true   # normalize diacritics in paths
preserveTaxonomyNames = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  mainSections = ["posts"]

#  [params.upvote]
#    enabled = true
#    endpoint = "/api/upvote"
#    infoEndpoint = "/api/upvote-info"
#    cookieDomain = ""

  [params.social]
#    linkedin = "https://www.linkedin.com/in/example"
    x = "https://x.com/nullc0py"
    github = "https://github.com/nullcopy"
    email = "hello@coldnoise.net"
    pgp = "/781C65EEE6ACD2BB7E0DB7691A6E2D470A6F6535.asc"  # Update with your actual PGP key URL
    zcash = "/zcash"

  [params.home]
    intro = """Hi, I'm John ðŸ‘‹. I'm an engineer that loves to build
            technologies that empower people. I tend to focus on privacy, p2p, and
            blockchain tech, but not exclusively... I try to add some diversity into my
            projects :)
            """

    [params.home.tags]
      # Set to 0 or negative to show all tags
      limit = 6

    [params.home.recent]
      limit = 8

[markup]
  [markup.goldmark.parser.attribute]
    block = true

  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    # Enable line numbers and render them in a table
    lineNos = true
    lineNumbersInTable = true
    anchorLineNos = false
    codeFences = true
    lineNoStart = 1
    noClasses = true

[build]
  [build.buildStats]
    enable = true

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

[[module.mounts]]
  source = 'assets'
  target = 'assets'

[[module.mounts]]
  source = 'hugo_stats.json'
  target = 'assets/watching/hugo_stats.json'
